#!/usr/bin/env python3
import sys
import help
import error_handling
import manage_algorithm

ac :int = len(sys.argv)
av :[str] = sys.argv

def transfer()->int:
    if ac == 2:
        if av[1] == "-h" or av[1] == "--help":
            help.help()
            sys.exit(0)
    if error_handling.error(ac, av) == -1:
        sys.exit(84)
    manage_algorithm.do_transfer(ac, av)
    sys.exit(0)

transfer()